trigger: none
pool: Dec22agent
stages:
  - stage: 
    displayName: terrform_tool
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Dec_2225'
            backendAzureRmResourceGroupName: 'Ashish_storage'
            backendAzureRmStorageAccountName: 'ashish23dec2025'
            backendAzureRmContainerName: 'asihshcon'
            backendAzureRmKey: 'ashishkey.tfstate'
        


